// Curated icon registry. We import only the icons we use (keeps the bundle lean
// for offline caching) and resolve them by name so guideline data can reference
// an icon with a string. Unknown names fall back to a stethoscope.

import {
  // category icons
  Wind,
  Soup,
  Bug,
  Activity,
  ShieldAlert,
  // guideline icons
  Stethoscope,
  HeartPulse,
  Flame,
  Pill,
  Syringe,
  Thermometer,
  Baby,
  Droplet,
  Droplets,
  Bone,
  Brain,
  TestTubes,
  Wind as Airway,
  Utensils,
  Milk,
  Bandage,
  Ambulance,
  Biohazard,
  // ui icons
  Search,
  ChevronRight,
  ChevronLeft,
  ArrowLeft,
  ArrowRight,
  RotateCcw,
  FileText,
  Download,
  Home,
  X,
  Info,
  TriangleAlert,
  OctagonAlert,
  CircleCheck,
  CircleHelp,
  Circle,
  Calculator,
  Phone,
  ClipboardList,
  ListChecks,
  Table,
  ExternalLink,
  ChevronDown,
  BookOpen,
  CircleAlert,
  Scale,
  CornerDownRight,
  CheckCheck,
} from "lucide-react";

const REGISTRY = {
  Wind,
  Soup,
  Bug,
  Activity,
  ShieldAlert,
  Stethoscope,
  HeartPulse,
  Flame,
  Pill,
  Syringe,
  Thermometer,
  Baby,
  Droplet,
  Droplets,
  Bone,
  Brain,
  TestTubes,
  Airway,
  Utensils,
  Milk,
  Bandage,
  Ambulance,
  Biohazard,
  Search,
  ChevronRight,
  ChevronLeft,
  ArrowLeft,
  ArrowRight,
  RotateCcw,
  FileText,
  Download,
  Home,
  X,
  Info,
  TriangleAlert,
  OctagonAlert,
  CircleCheck,
  CircleHelp,
  Circle,
  Calculator,
  Phone,
  ClipboardList,
  ListChecks,
  Table,
  ExternalLink,
  ChevronDown,
  BookOpen,
  CircleAlert,
  Scale,
  CornerDownRight,
  CheckCheck,
};

export function Icon({ name, ...props }) {
  const Cmp = REGISTRY[name] || Stethoscope;
  return <Cmp {...props} />;
}

export function hasIcon(name) {
  return !!REGISTRY[name];
}
